### ISSUE TITLE
Pipenv issues

### ISSUE THREAD

**Issue by wongjustin99** [modalblunder/ftd-analysis#2]
Had some trouble getting this running with Pipenv, so I converted it to use venv instead. 

requirements.txt if it's of any use to anyone else

```
certifi==2024.7.4
distlib==0.3.8
filelock==3.15.4
numpy==2.0.0
pandas==2.2.2
pbr==6.0.0
pipenv==2024.0.1
pipenv-to-requirements==0.9.0
platformdirs==4.2.2
python-dateutil==2.9.0.post0
pytz==2024.1
setuptools==70.2.0
six==1.16.0
tzdata==2024.1
virtualenv==20.26.3
```

**Comment by modalblunder** [comment]
What sort of issues did you have with pipenv? Nonetheless, I adding a requirements.txt for folks who are more comfortable with venv.

https://github.com/modalblunder/ftd-analysis/commit/0a969686bc2b2c0ad44c0bd8932565cbca0fd299
